### ISSUE TITLE
Allow configuring whether `wasm-opt` is required or not

### ISSUE THREAD

**Issue by fitzgen** [xtuc/rust-plugin#2]
In some situations it makes sense to only run `wasm-opt` if it is available, in others it makes sense to require that it is present and make it a fatal error when it is missing. We should have a flag in the config options to control this behavior.

**Comment by xtuc** [comment]
Ok, what should be the configuration?

Maybe something like:
```js
new RustPlugin({
    wasmopt: {
        required: true
    }
})
```

**Comment by fitzgen** [comment]
Looks perfect!
